# Generated by Django 4.2.1 on 2023-05-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
    ]
