# Generated by Django 4.2.1 on 2023-06-10 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_socio_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='descripcion',
            field=models.CharField(max_length=800),
        ),
    ]
